# Site config
name: "RJ226"
tagline: "Helping YOU build better in Minecraft"
description: "RJ226 helps you become a great builder in Minecraft using some of things that I have learnt from my time playing Minecraft and from watching others."
author: "RJ226"
logo: "/ms-icon-310x310.png"
lang: en_GB

# Social profiles
social:
  name: RJ226
  links:
    - https://www.youtube.com/channel/UC3J585n81BMItgouCZOZi_w
    - https://twitter.com/226Rj
    - https://www.reddit.com/r/RJ226/
    - https://discord.gg/cBUVsja

# Outputting
baseurl: ""
timezone: "Europe/London"
permalink: "/:categories/:title"

# Site config
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      layout: "default"
  -
    scope:
      path: "_posts/playlists"
      type: "posts"
    values:
      layout: "playlist"
      category: playlists
      playlist:
        type: "Playlist"
        channel: "RJ226"
